
# Loader metadata
modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/alcatrazEscapee/suck-eggs/issues" #optional

[[mods]]
    modId="suckeggs" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Suck Eggs" #mandatory
    #updateJSONURL="http://myurl.me/" #optional
    displayURL="https://minecraft.curseforge.com/projects/suck-eggs" #optional
    #logoFile="icon.png" #optional
    credits="As requested by reddit." #optional
    authors="AlcatrazEscapee" #optional
    description='''
    You can now suck eggs. Yeah. That's basically it.
    '''

# dependencies
[[dependencies.suckeggs]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.suckeggs]]
    modId="minecraft" #mandatory
    mandatory=true #mandatory
    versionRange="[1.16.1,)" #mandatory
    ordering="NONE"
    side="BOTH"